## Continution to Previous Numpy Notebook 
(c) Dr. Naveen Aggarwal

In [2]:
import numpy as np

## Broadcasting Example

Broadcasting in NumPy is the mechanism by which arrays with different shapes are treated as having the same shape for the purpose of performing arithmetic operations.

Here's a simple example to illustrate how broadcasting works in NumPy:

In [2]:
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])

# Broadcasting the smaller array 'a' to match the shape of 'b'
c = a + b
print(c)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


###### In the above example, the 1D array a is broadcasted to match the shape of the 2D array b, resulting in a 2D array c. Broadcasting allows us to perform arithmetic operations between arrays with different shapes, which is a convenient and efficient way to perform operations without having to manually reshape the arrays.

###### Broadcasting is not allowed when the shapes of the arrays being broadcasted do not have the same number of dimensions or when the dimensions have incompatible sizes. Here's an example of when broadcasting is not allowed:

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])

# Broadcasting the arrays 'a' and 'b' will raise a ValueError
c = a + b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

###### Another Example

In [4]:
x = np.arange(4)
print("x =",x)
xx = x.reshape(4,1)
print("xx =",xx)
y = np.ones(5)
print("y =",y)
z = np.ones((3,4))
print("z =",z)

x = [0 1 2 3]
xx = [[0]
 [1]
 [2]
 [3]]
y = [1. 1. 1. 1. 1.]
z = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
print(x.shape, xx.shape, y.shape,z.shape)

(4,) (4, 1) (5,) (3, 4)


In [6]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [8]:
xxy=xx+y
print(xxy)
print(xx.shape)
print(y.shape)
print(xxy.shape)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
(4, 1)
(5,)
(4, 5)


In [9]:

xz=x+z
print(xz)
print(x.shape)
print(z.shape)
print(xz.shape)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
(4,)
(3, 4)
(3, 4)


## Vectorization
##### Vectorization in NumPy is the process of transforming a scalar operation into a vector operation, allowing for operations to be performed on entire arrays instead of individual elements. This results in faster and more efficient computation, as the operation is performed in a single step instead of in a loop.

###### Here's a simple example to illustrate the difference between a scalar operation and a vectorized operation in NumPy:

In [ ]:
# Defining an array
a = np.array([1, 2, 3, 4])

# Scalar operation
b = []
for i in a:
    b.append(i * 2)
print(b)

d = []
for i in a:
    d.append(i*3)
print(d)

# Vectorized operation
c = a * 2
print(c)

[np.int64(2), np.int64(4), np.int64(6), np.int64(8)]
[np.int64(3), np.int64(6), np.int64(9), np.int64(12)]
[2 4 6 8]


#### Now Check the difference in time taken by normal dot product and numpy dot product.

In [ ]:
import time
x1=np.arange(0, 1000000, 0.1)
x2=np.arange(0, 1000000, 0.1)
#x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0,6, 7, 8, 9, 0, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6,7, 8, 9]
#x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0,7,8, 9, 4, 5, 6, 7, 8, 9,8, 5, 4, 5, 3, 8, 9, 5, 5]
### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot)+ "\n ----- Computation time = " + str(1*(toc - tic)) + "ms")


dot = 3.3333328333395686e+18
 ----- Computation time = 7.40625ms


In [21]:

tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1*(toc - tic)) + "ms")

dot = 3.3333328333332024e+18
 ----- Computation time = 0.0ms


## 1 - Building basic functions with numpy ##

sigmoid function, np.exp() ###

Before using np.exp(), lets use math.exp() to implement the sigmoid function. You will then see why np.exp() is preferable to math.exp().


$sigmoid(x) = \frac{1}{1+e^{-x}}$ is sometimes also known as the logistic function. It is a non-linear function used not only in Machine Learning (Logistic Regression), but also in Deep Learning.

<img src="images/Sigmoid.png" style="width:500px;height:228px;">

To refer to a function belonging to a specific package you could call it using package_name.function(). Run the code below to see an example with math.exp().

In [12]:
import math
#import numpy as np
def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    """
     
    s = 1/(1+math.exp(-x))
    #s1=1/(1+np.exp(-x))
    
    return s 

In [13]:
basic_sigmoid(3)

0.9525741268224334

In [14]:
### One reason why we use "numpy" instead of "math" in Deep Learning ###
x = [1, 2, 3]
basic_sigmoid(x) # you will see this give an error when you run it, because x is a vector.

TypeError: bad operand type for unary -: 'list'

In [20]:
y=[]
for ele in x:
    y.append(basic_sigmoid(ele))
print(y)

[0.7310585786300049, 0.8807970779778823, 0.9525741268224334]


In [16]:
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


In [18]:
def np_sigmoid(x):
    """
    Compute sigmoid of x.

    """
     
    s1=1/(1+np.exp(-x))
    
    return s1 

In [30]:
print(np_sigmoid(x))

[0.73105858 0.88079708 0.95257413]
