1. Create one hot encoding of an array. For example For an array([2, 3, 2, 2, 2, 1]) 
Output should be array([[ 0., 1., 0.], [ 0., 0., 1.], [ 0., 1., 0.], [ 0., 1., 0.], [ 0., 1., 0.], [ 1., 0., 0.]])

In [21]:
import numpy as np

arr = np.array([2, 3, 2, 2, 2, 1])
encoded_arr = np.zeros((arr.size, arr.max()+1), dtype= int)
encoded_arr[np.arange(arr.size),arr] = 1

print("One Hot Encoded Array:")
print(encoded_arr)


One Hot Encoded Array:
[[0 0 1 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 1 0 0]]


2.Drop all missing values from an array Input: np.array([1,2,3,np.nan,5,6,7,np.nan]) Desired Output: array([ 1.,2.,3.,5.,6.,7.])

In [22]:
import numpy as np

arr = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])

modify_arr = arr[~np.isnan(arr)]

print("After Removing NaN:")
print(modify_arr)


After Removing NaN:
[1. 2. 3. 5. 6. 7.]


3.Find Index of Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) Desired Output: array([2, 5])

In [23]:
import numpy as np

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

grad = np.gradient(a)
print(grad)

#  local maxima
local_maxima = np.where((grad[:-1]>0)&(grad[1:]<0))[0] +1

print("Index of Local Maxima:")
print(local_maxima)



[ 2.   3.  -1.  -2.5  2.5 -1.  -2.5  1. ]
Index of Local Maxima:
[2 5]


4. From the given 1d array arr, generate a 2d matrix using strides, For example for an array ([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])with a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..] w and s will be provided by user Calculate the moving average.

In [24]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
print(arr.size)

w = int(input("Enter window size: "))
s = int(input("Enter stride: "))


windows = []

for i in range(0, len(arr) - w + 1, s):
    windows.append(arr[i:i+w])

windows = np.array(windows)

print("Generated 2D Matrix:")
print(windows)


moving_avg = np.mean(windows, axis=1)

print("Moving Average:")
print(moving_avg)


15
Generated 2D Matrix:
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
Moving Average:
[ 1.5  3.5  5.5  7.5  9.5 11.5]
