Question 1. Create a function to check whether numpy array has Zero values or not. 

In [ ]:
# Method 1- using function 

import numpy as np
import random

size = int(input("Enter the size of array"))
a = 0 
b = 10
# num = random.choices(range(a,b), k= size)
# print(num)

array = np.random.randint(a,b,size= size).tolist()
print(array)

def check_zero_in_array(array):
    flag = False
    for i in array:
        if (i == 0 ):
            flag = True
    return flag

if (check_zero_in_array(array) == True):
    print("Yes, it contains zero.")
else:
    print("No, it don't contain any zero.")

[4, 7, 3, 7, 9, 4, 2, 7, 7, 9]
No, it don't contain any zero.


In [17]:
# Method 2 using (in) function 
print(0 in array)

False


In [18]:
# Method 3 using any function
has_zero = np.any(array == 0)
print(has_zero)

False


Q2 ). Consider an array contains marks of students. Find the median and mean of students who got passing marks.

In [34]:
import numpy as np
import random

size = int(input("Enter the number of students "))
low = 0
high = 100

marks = np.random.randint(low, high, size=size).tolist()
print(f"Marks of the students:",marks)

marks = np.array(marks)
passing_mark = 40
pass_array = np.array([])

pass_array = np.append(pass_array, marks[marks > passing_mark])
pass_array = pass_array.astype(int)
print(f"Passing marks: ",pass_array)

mean_value = np.mean(pass_array)
print(f"Mean: {mean_value:.2f}")
median_value = np.median(pass_array)
print(f"Median: {median_value:.2f}")


Marks of the students: [50, 2, 7, 80, 3, 94, 24, 79, 99, 32]
Passing marks:  [50 80 94 79 99]
Mean: 80.40
Median: 80.00


Q3. Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.

In [ ]:
import numpy as np

dob = np.array([
    '2008-02-05', 
    '2007-04-12',  
    '2006-06-20',  
    '2005-09-15', 
    '2012-03-10',  
    '1999-12-25'  
], dtype='datetime64')

print("DOB:", dob)
# today date
today = np.datetime64('today')
print("Current Date:", today)

# making an array
ages = []
for d in dob:
    age = (today - d).astype('timedelta64[Y]').astype(int)
    ages.append(age) # appending value in it

# then making this array as an numpy array 
ages = np.array(ages) 
print("Ages:", ages)

# labelling
labels = []

for age in ages:
    if age == 18:
        labels.append("First")
    elif age == 19:
        labels.append("Second")
    elif age == 20:
        labels.append("Third")
    elif age == 21:
        labels.append("Fourth")
    else:
        labels.append("Not in range")

labels = np.array(labels)
print("Labels:", labels)


DOB: ['2008-02-05' '2007-04-12' '2006-06-20' '2005-09-15' '2012-03-10'
 '1999-12-25']
Current Date: 2026-02-10
Ages: [18 18 19 20 13 26]
Labels: ['First' 'First' 'Second' 'Third' 'Not in range' 'Not in range']


4.Create a function to sort 2d Array by a column.


In [11]:
import numpy as np

def sort_by_column(arr, col_index):
    col = col_index
    index = np.argsort(arr[:,col])
    return arr[index]

array = np.array([
    [10, 3, 5],
    [2, 8, 1],
    [7, 4, 9],
    [5, 6, 2]
])

print("Original Array:")
print(array)

column = int(input("Enter the column "))
sorted_array = sort_by_column(array, column)

print(f"\nSorted Array by Column {column}:")
print(sorted_array)


Original Array:
[[10  3  5]
 [ 2  8  1]
 [ 7  4  9]
 [ 5  6  2]]

Sorted Array by Column 0:
[[ 2  8  1]
 [ 5  6  2]
 [ 7  4  9]
 [10  3  5]]
