In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:

brr = [1,3,5,7,9]
grr = np.array(brr)
print(grr)

[1 3 5 7 9]


In [6]:
print(np.__version__)
print(type(arr))
print(arr.dtype)

2.0.2
<class 'numpy.ndarray'>
int64


In [7]:
a = np.array((1,2,3,4,5,6,7))
print(a)

[1 2 3 4 5 6 7]


In [12]:
# 0-D Array
a = np.array(21)
print(a)
print(type(a))
print(a.dtype)

# 1-D Array
b = np.array([1,2,3,4,5])
print(b)
print(type(b))
print(b.dtype)

# 2-D Array
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(type(c))
print(c.dtype)

# 3-D Array
d = np.array([[[1,3],[3,4]],[[1,2],[9,1]]])
print(d)

21
<class 'numpy.ndarray'>
int64
[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
[[[1 3]
  [3 4]]

 [[1 2]
  [9 1]]]


In [13]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
arr = np.array([1,2,3,4],ndmin = 5)
print(arr)

[[[[[1 2 3 4]]]]]


In [19]:
print(b)
print(b[2])
print(b[2]+b[3])

[1 2 3 4 5]
3
7


In [21]:
print(d[1,-1])

[9 1]
